//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.08 at 07:23:44 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.response.app.customer.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.customer.app.response;
