
package com.sun.mdm.index.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-03-08T19:23:46.455+02:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "ProcessingException", targetNamespace = "http://webservice.index.mdm.sun.com/")
public class ProcessingException_Exception extends Exception {

    private com.sun.mdm.index.webservice.ProcessingException processingException;

    public ProcessingException_Exception() {
        super();
    }

    public ProcessingException_Exception(String message) {
        super(message);
    }

    public ProcessingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ProcessingException_Exception(String message, com.sun.mdm.index.webservice.ProcessingException processingException) {
        super(message);
        this.processingException = processingException;
    }

    public ProcessingException_Exception(String message, com.sun.mdm.index.webservice.ProcessingException processingException, java.lang.Throwable cause) {
        super(message, cause);
        this.processingException = processingException;
    }

    public com.sun.mdm.index.webservice.ProcessingException getFaultInfo() {
        return this.processingException;
    }
}
