
package com.sun.mdm.index.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-03-08T19:23:46.503+02:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "PageException", targetNamespace = "http://webservice.index.mdm.sun.com/")
public class PageException_Exception extends Exception {

    private com.sun.mdm.index.webservice.PageException pageException;

    public PageException_Exception() {
        super();
    }

    public PageException_Exception(String message) {
        super(message);
    }

    public PageException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PageException_Exception(String message, com.sun.mdm.index.webservice.PageException pageException) {
        super(message);
        this.pageException = pageException;
    }

    public PageException_Exception(String message, com.sun.mdm.index.webservice.PageException pageException, java.lang.Throwable cause) {
        super(message, cause);
        this.pageException = pageException;
    }

    public com.sun.mdm.index.webservice.PageException getFaultInfo() {
        return this.pageException;
    }
}
